import { asQuestionId } from '@physicsos/shared'
import type { QuestionDocument } from './question-document.ts'

export interface GoldenQuestionDefinition {
  id: string
  title: string
  text: string
  expectedDomain?: 'magnetic' | 'mechanics' | 'electric' | 'composite'
  expectedChargeSign: 'positive' | 'negative' | 'unknown'
  expectedFieldDirection: 'into_page' | 'out_of_page' | 'unknown'
  expectedValidation: 'VALID' | 'AMBIGUOUS' | 'INVALID_SEMANTICS' | 'UNSUPPORTED_MODEL'
  /** Composite apparatus the question describes, when it is a composite one. */
  expectedModel?: 'velocity_selector' | 'mass_spectrometer' | 'charged_particle_composite_field' | 'cyclotron'
}

export const GOLDEN_QUESTIONS: readonly GoldenQuestionDefinition[] = [
  {
    id: '01-proton-basic',
    title: '质子垂直进入匀强磁场',
    text: '一个质子以 2.0×10^6 m/s 的速度，垂直进入磁感应强度为 0.50 T，方向垂直纸面向里的匀强磁场。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：1. 洛伦兹力大小 2. 轨道半径 3. 运动周期 4. 判断运动方向 5. 显示运动轨迹',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: '02-electron-negative-charge',
    title: '电子垂直进入匀强磁场',
    text: '一个电子以 2.0×10^6 m/s 的速度，垂直进入磁感应强度为 0.50 T，方向垂直纸面向里的匀强磁场。已知：m = 9.11×10^-31 kg，q = -1.60×10^-19 C。求：1. 洛伦兹力大小 2. 轨道半径 3. 运动周期 4. 判断运动方向',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: '03-field-out-of-page',
    title: '磁场垂直纸面向外',
    text: '一个质子以 1.0×10^6 m/s 的速度，垂直进入磁感应强度为 0.40 T，方向垂直纸面向外的匀强磁场。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：1. 轨道半径 2. 运动周期 3. 判断运动方向',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: '04-radius-only',
    title: '仅求轨道半径',
    text: '一个质子以 3.0×10^6 m/s 的速度，垂直进入磁感应强度为 0.20 T，方向垂直纸面向里的匀强磁场。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：轨道半径',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: '05-period-only',
    title: '仅求运动周期',
    text: '一个质子以 5.0×10^5 m/s 的速度，垂直进入磁感应强度为 0.30 T，方向垂直纸面向里的匀强磁场。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：运动周期',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: '06-missing-charge-sign',
    title: '缺少电荷正负',
    text: '一个带电粒子以 2.0×10^6 m/s 的速度，垂直进入磁感应强度为 0.50 T，方向垂直纸面向里的匀强磁场。已知：m = 1.67×10^-27 kg，q = 1.60×10^-19 C。求：1. 轨道半径 2. 判断运动方向',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'AMBIGUOUS',
  },
  {
    id: '07-zero-field',
    title: '磁感应强度为零',
    text: '一个质子以 2.0×10^6 m/s 的速度进入磁感应强度为 0 T 的区域。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：轨道半径',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'INVALID_SEMANTICS',
  },
  {
    id: '08-parallel-velocity',
    title: '速度与磁场平行',
    text: '一个质子以 2.0×10^6 m/s 的速度，平行于磁感应强度为 0.50 T 的匀强磁场方向运动。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：轨道半径',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'UNSUPPORTED_MODEL',
  },
  {
    id: '09-unit-conversion',
    title: '单位转换',
    text: '一个质子以 2000 km/s 的速度，垂直进入磁感应强度为 500 mT，方向垂直纸面向里的匀强磁场。已知：m = 1.67×10^-27 kg，q = +1.60×10^-19 C。求：轨道半径和运动周期',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: '10-scientific-notation',
    title: '科学计数法',
    text: '一个质子以 2.0e6 m/s 的速度，垂直进入磁感应强度为 0.50 T，方向垂直纸面向里的匀强磁场。已知：m = 1.67e-27 kg，q = +1.60e-19 C。求：1. 洛伦兹力大小 2. 轨道半径 3. 运动周期',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-01-perpendicular-deflection',
    title: '正电荷在匀强电场中偏转',
    text: '一个带正电粒子，质量 m = 4 kg，电荷量 q = +2 C，初速度为 3 m/s，沿 x 轴正方向进入匀强电场。电场强度 E = 6 N/C，电场方向沿 y 轴正方向，运动 2 s。求电场力、加速度、末速度、位移、电势变化、电势能变化、电场力做功和动能变化。',
    expectedDomain: 'electric',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-02-negative-parallel',
    title: '负电荷沿电场方向减速',
    text: '一个带负电粒子，质量 m = 2 kg，电荷量 q = -1 C，初速度为 4 m/s，沿 x 轴正方向运动。空间存在匀强电场，电场强度 E = 2 V/m，电场方向沿 x 轴正方向，运动 2 s。求电场力、加速度、末速度、位移、电势变化、电势能变化和动能变化。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-03-point-charge-field',
    title: '点电荷的电场强度',
    text: '一个点电荷 q = +5 μC，在距其 r = 20 cm 处放一个试探电荷。求该点的电场强度大小。',
    expectedDomain: 'electric',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-04-point-charge-force',
    title: '点电荷对试探电荷的电场力',
    text: '一个点电荷 q = +5 μC，在距其 r = 20 cm 处放一个试探电荷 q\' = +2 μC。求试探电荷受到的电场力。',
    expectedDomain: 'electric',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-05-point-charge-direction',
    title: '负点电荷的电场方向',
    text: '一个点电荷 q = -3 μC，在距其 r = 10 cm 处放一个试探电荷，判断该点电场方向。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-06-dipole-midpoint-field',
    title: '等量异种点电荷中点的电场强度',
    text: '两个点电荷 q1 = +2 μC，q2 = -2 μC，相距 20 cm。求两电荷连线中点处的电场强度大小。',
    expectedDomain: 'electric',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-07-like-charges-midpoint',
    title: '等量同种点电荷中点的电场强度',
    text: '两个点电荷 q1 = +3 μC，q2 = +3 μC，相距 30 cm。求两电荷连线中点处的电场强度大小。',
    expectedDomain: 'electric',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-08-dipole-axis-field',
    title: '电偶极子中点的电场强度',
    text: '两个点电荷 q1 = +1 μC，q2 = -1 μC，相距 10 cm。求两电荷连线中点处的电场强度大小。',
    expectedDomain: 'electric',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-09-off-axis-field',
    title: '点电荷轴外的电场强度',
    text: '一个点电荷 q = +4 μC，在距其左侧 15 cm 处放一个试探电荷。求该点的电场强度大小与方向。',
    expectedDomain: 'electric',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-10-electron-deflection',
    title: '电子在平行板电场中的偏转距离',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 12 cm。求电子的偏转距离。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-11-proton-deflection',
    title: '质子在平行板电场中的偏转',
    text: '一个质子以初速度 v0 = 2×10^6 m/s 水平射入平行板电场。已知质子质量 m = 1.67×10^-27 kg，电荷量 q = +1.6×10^-19 C，电场强度 E = 5000 V/m，方向竖直向下，板间距 d = 2 cm，板长 L = 10 cm。求质子的偏转距离。',
    expectedDomain: 'electric',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-12-exit-velocity',
    title: '离开平行板电场时的速度',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 12 cm。求电子离开电场时的速度大小。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-13-hit-plate-time',
    title: '电子打到极板的时间',
    text: '一个电子以初速度 v0 = 1×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 5000 V/m，方向竖直向下，板间距 d = 2 cm，板长 L = 20 cm。求电子打到极板的时间。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-14-deflection-direction',
    title: '电子偏转方向判断',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 12 cm。判断电子的偏转方向（向上或向下）。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-15-field-reversed',
    title: '电场反向后的偏转方向',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向上，板间距 d = 4 cm，板长 L = 12 cm。判断电子的偏转方向。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-16-different-velocity',
    title: '不同初速度对偏转的影响',
    text: '两个电子分别以初速度 v0 = 3×10^7 m/s 和 v0 = 1.5×10^7 m/s 水平射入相同的平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 12 cm。比较两个电子的偏转距离大小关系。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-17-different-charge',
    title: '不同电荷量的偏转比较',
    text: '一个电子和一个质子以相同初速度 v0 = 2×10^6 m/s 水平射入相同的平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，质子质量 m = 1.67×10^-27 kg，电荷量 q = +1.6×10^-19 C，电场强度 E = 5000 V/m，方向竖直向下，板间距 d = 2 cm，板长 L = 10 cm。比较两者的偏转距离。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-18-plate-length-effect',
    title: '板长对偏转的影响',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 6 cm。求电子的偏转距离，并与板长为 12 cm 时的偏转距离比较。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'electric-19-energy',
    title: '平行板电场中电场力做功与动能变化',
    text: '一个电子以初速度 v0 = 3×10^7 m/s 水平射入平行板电场。已知电子质量 m = 9.11×10^-31 kg，电荷量 q = -1.6×10^-19 C，电场强度 E = 2000 V/m，方向竖直向下，板间距 d = 4 cm，板长 L = 12 cm。求电场力对电子做的功和电子动能的变化。',
    expectedDomain: 'electric',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-01-uniform-acceleration',
    title: '匀加速直线运动',
    text: '汽车初速度为 10 m/s，加速度为 2 m/s²，运动 5 s。求末速度和位移。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-02-projectile-horizontal',
    title: '平抛运动',
    text: '物体从 20 m 高处，以 10 m/s 水平抛出，g = 10 m/s²。求落地时间和水平射程。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-03-projectile-oblique',
    title: '斜抛运动',
    text: '物体以初速度 20 m/s，抛射角 30° 抛出，g = 10 m/s²。求最大高度、飞行时间和射程。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-04-newton-second-law',
    title: '牛顿第二定律',
    text: '质量为 2 kg 的物体受到水平合力 10 N。求加速度。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-05-incline-no-friction',
    title: '无摩擦斜面',
    text: '质量为 2 kg 的物体在倾角 30° 的光滑斜面上，g = 10 m/s²。求沿斜面加速度和支持力。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },
  {
    id: 'mech-06-unit-conversion',
    title: '单位转换 72km/h',
    text: '汽车以 72 km/h 的速度行驶，加速度为 2 m/s²，运动 5 s。求末速度。',
    expectedChargeSign: 'unknown',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'VALID',
  },

  /* ------------------------------------------------------------- composite -- *
   * Crossed-field apparatuses: a velocity selector, a mass spectrometer, and
   * E+B / E+B+g worlds. Every question states the charge sign, the electric-field
   * direction and the magnetic-field orientation, because those three are what
   * turn magnitudes into a force balance — without them the apparatus geometry is
   * undetermined and the IR is legitimately AMBIGUOUS rather than solvable.
   * Field magnitudes are chosen so the selection condition is exact
   * (v = E/B) unless the question is specifically about a rejected particle.       */

  {
    id: 'comp-01-selector-balance',
    title: '速度选择器：恰好通过',
    text: '速度选择器中有互相垂直的匀强电场和匀强磁场，电场方向竖直向上，E = 2.0×10^4 V/m，磁场方向垂直纸面向外，B = 0.20 T。一个正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 沿水平方向从左端射入，沿直线通过。求：1. 电场力大小 2. 洛伦兹力大小 3. 合力大小',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-02-selector-selected-velocity',
    title: '速度选择器：求选择速度',
    text: '速度选择器的电场方向竖直向上，电场强度 E = 4.0×10^4 V/m，磁场方向垂直纸面向外，磁感应强度 B = 0.50 T。一束正离子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）沿水平方向射入。求能够沿直线通过的粒子速度大小。',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-03-selector-too-fast',
    title: '速度选择器：速度偏大',
    text: '速度选择器中电场方向竖直向上，E = 2.0×10^4 V/m，磁场方向垂直纸面向外，B = 0.20 T。一个正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 2.0×10^5 m/s 水平射入。求：1. 电场力大小 2. 洛伦兹力大小 3. 合力大小 4. 画出运动轨迹',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-04-selector-too-slow',
    title: '速度选择器：速度偏小',
    text: '速度选择器中电场方向竖直向上，E = 2.0×10^4 V/m，磁场方向垂直纸面向外，B = 0.20 T。一个正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 5.0×10^4 m/s 水平射入。求：1. 电场力大小 2. 洛伦兹力大小 3. 合力大小',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-05-selector-electron',
    title: '速度选择器：电子通过',
    text: '速度选择器中电场方向竖直向上，E = 1.0×10^4 V/m，磁场方向垂直纸面向里，B = 0.10 T。一个电子（q = -1.6×10^-19 C，m = 9.11×10^-31 kg）以 v = 1.0×10^5 m/s 水平向右射入，恰好沿直线通过。求：1. 电场力大小 2. 洛伦兹力大小',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-06-selector-low-field',
    title: '速度选择器：弱场',
    text: '速度选择器中电场方向竖直向上，E = 200 V/m，磁场方向垂直纸面向外，B = 2.0×10^-3 T。质子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 水平射入并沿直线通过。求：1. 选择速度 2. 电场力大小 3. 合力大小',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-07-selector-trajectory',
    title: '速度选择器：轨迹与合力',
    text: '在速度选择器中，电场方向竖直向下，E = 3.0×10^4 V/m，磁场方向垂直纸面向里，B = 0.30 T。正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 水平向右射入。求：1. 合力大小 2. 运动轨迹 3. 加速度',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-08-selector-missing-direction',
    title: '速度选择器：未给磁场方向',
    text: '速度选择器中电场方向竖直向上，E = 2.0×10^4 V/m，磁感应强度 B = 0.20 T。正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 水平射入。求电场力大小。',
    expectedDomain: 'composite',
    expectedModel: 'velocity_selector',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'unknown',
    expectedValidation: 'AMBIGUOUS',
  },
  {
    id: 'comp-09-spectrometer-radius',
    title: '质谱仪：偏转半径',
    text: '质谱仪由速度选择器和偏转磁场组成。速度选择器的电场方向竖直向上，E = 200 V/m，磁场方向垂直纸面向外，B = 2.0×10^-3 T。质子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 水平射入并沿直线通过选择器，随后进入偏转磁场做圆周运动。求：1. 圆周半径 2. 洛伦兹力大小',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-10-spectrometer-charge-mass',
    title: '质谱仪：荷质比',
    text: '在质谱仪中，速度选择器的电场方向竖直向上，E = 200 V/m，磁场方向垂直纸面向外，B = 2.0×10^-3 T。一个正离子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 通过选择器后进入偏转磁场，测得圆周半径 r = 0.52 m。求该离子的荷质比。',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-11-spectrometer-isotope',
    title: '质谱仪：同位素分离',
    text: '质谱仪用于分离同位素。速度选择器电场方向竖直向上，E = 200 V/m，磁场方向垂直纸面向外，B = 2.0×10^-3 T，正离子 q = 1.6×10^-19 C，m = 3.34×10^-27 kg，以 v = 1.0×10^5 m/s 通过选择器进入偏转磁场。求：1. 圆周半径 2. 回旋周期',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-12-spectrometer-period',
    title: '质谱仪：回旋周期',
    text: '质谱仪的速度选择器电场方向竖直向上，E = 400 V/m，磁场方向垂直纸面向外，B = 4.0×10^-3 T。质子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）以 v = 1.0×10^5 m/s 沿直线通过后进入偏转磁场。求：1. 回旋周期 2. 圆周半径',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-13-spectrometer-electron',
    title: '质谱仪：电子束偏转',
    text: '质谱仪中速度选择器的电场方向竖直向上，E = 100 V/m，磁场方向垂直纸面向里，B = 1.0×10^-3 T。电子（q = -1.6×10^-19 C，m = 9.11×10^-31 kg）以 v = 1.0×10^5 m/s 水平向右通过选择器，进入偏转磁场。求：1. 圆周半径 2. 洛伦兹力大小',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-14-spectrometer-selected-velocity',
    title: '质谱仪：选择速度与半径',
    text: '质谱仪的速度选择器电场方向竖直向上，E = 300 V/m，磁场方向垂直纸面向外，B = 3.0×10^-3 T，正离子 q = 1.6×10^-19 C，m = 1.67×10^-27 kg。求：1. 能够通过选择器的粒子速度 2. 进入偏转磁场后的圆周半径',
    expectedDomain: 'composite',
    expectedModel: 'mass_spectrometer',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-15-eb-crossed',
    title: '复合场：E 与 B 同时作用',
    text: '一个正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）同时受到匀强电场和匀强磁场作用，电场方向竖直向上，E = 2.0×10^4 V/m，磁场方向垂直纸面向里，B = 0.20 T，粒子以 v = 1.0×10^5 m/s 水平向右射入，不计重力。求：1. 电场力大小 2. 洛伦兹力大小 3. 合力大小 4. 加速度',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-16-eb-electron-trajectory',
    title: '复合场：电子在正交场中的轨迹',
    text: '电子（q = -1.6×10^-19 C，m = 9.11×10^-31 kg）在互相垂直的电场和磁场中运动，电场方向竖直向下，E = 1.0×10^3 V/m，磁场方向垂直纸面向外，B = 0.010 T，初速度 v = 1.0×10^5 m/s 水平向右，不计重力。求：1. 合力大小 2. 运动轨迹 3. 动能变化',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-17-eb-energy',
    title: '复合场：动能与洛伦兹力做功',
    text: '正电粒子（q = 1.6×10^-19 C，m = 1.67×10^-27 kg）同时处于匀强电场与匀强磁场中，电场方向竖直向上，E = 5.0×10^3 V/m，磁场方向垂直纸面向里，B = 0.050 T，初速度 v = 1.0×10^5 m/s 水平向右，不计重力。求：1. 动能 2. 动能变化 3. 合力大小',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'into_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-18-ebg-balance',
    title: '复合场：电场、磁场与重力平衡',
    text: '一个带正电的微粒（q = 1.0×10^-6 C，m = 2.0×10^-6 kg）同时受到匀强电场、匀强磁场和重力作用，电场方向竖直向上，E = 20 V/m，磁场方向垂直纸面向外，B = 0.20 T，重力加速度 g = 10 m/s²，以 v = 100 m/s 水平向右射入。求：1. 电场力大小 2. 洛伦兹力大小 3. 合力大小',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-19-ebg-droplet',
    title: '复合场：带电液滴三力叠加',
    text: '带负电的液滴（q = -2.0×10^-6 C，m = 4.0×10^-6 kg）同时存在电场、磁场和重力，电场方向竖直向下，E = 10 V/m，磁场方向垂直纸面向外，B = 0.20 T，g = 10 m/s²，以 v = 50 m/s 水平向右射入。求：1. 合力大小 2. 加速度 3. 运动轨迹',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'negative',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-20-ebg-heavy-particle',
    title: '复合场：三场中的带电微粒',
    text: '带正电的微粒（q = 5.0×10^-7 C，m = 1.0×10^-6 kg）同时受到电场力、洛伦兹力和重力，电场方向竖直向上，E = 20 V/m，磁场方向垂直纸面向外，B = 0.20 T，重力加速度 g = 10 m/s²，以 v = 100 m/s 水平向右射入。求：1. 电场力大小 2. 合力大小 3. 加速度',
    expectedDomain: 'composite',
    expectedModel: 'charged_particle_composite_field',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'VALID',
  },
  {
    id: 'comp-21-cyclotron-unsupported',
    title: '回旋加速器（当前引擎不支持）',
    text: '回旋加速器的匀强磁场方向垂直纸面向外，B = 1.5 T，加速电场频率与质子回旋频率相同。质子 q = 1.6×10^-19 C，m = 1.67×10^-27 kg，以 v = 1.0×10^5 m/s 开始加速。求：1. 回旋周期 2. 最大速度',
    expectedDomain: 'composite',
    expectedModel: 'cyclotron',
    expectedChargeSign: 'positive',
    expectedFieldDirection: 'out_of_page',
    expectedValidation: 'UNSUPPORTED_MODEL',
  },
]

export function createGoldenQuestionDocument(def: GoldenQuestionDefinition, now?: string): QuestionDocument {
  const ts = now ?? new Date().toISOString()
  const domain = def.expectedDomain ?? (def.id.startsWith('mech-') ? 'mechanics' : 'magnetic')
  return {
    id: asQuestionId('golden-' + def.id),
    content: {
      source: 'text',
      rawText: def.text,
      extractedText: def.text,
      status: 'EXTRACTED',
    },
    metadata: {
      title: def.title,
      tags: [domain, domain === 'mechanics' ? 'motion' : 'charged-particle'],
      difficulty: 'standard',
    },
    createdAt: ts,
    updatedAt: ts,
  }
}
