import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { resolveReleaseConfig, validateReleaseConfig } from './release-lib.mjs'

const repoRoot = fileURLToPath(new URL('../..', import.meta.url))
const desktopRoot = `${repoRoot}apps/desktop/`
const vendorRoot = `${repoRoot}vendor/deepseek-harness/`
// vendor/deepseek-harness/apps/web/dist is the canonical Vite output.
const frontendDist = `${vendorRoot}apps/web/dist`
const desktopFrontendDist = `${desktopRoot}web-release`
const releaseConfigPath =
  process.env.PHYSICSOS_DESKTOP_RELEASE_CONFIG ?? `${desktopRoot}release.config.json`
const pnpmEnvironment = {
  ...process.env,
  pnpm_config_verify_deps_before_run: 'false',
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    env: pnpmEnvironment,
    stdio: 'inherit',
    ...options,
  })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
  return result
}

const baseConfig = JSON.parse(readFileSync(`${desktopRoot}src-tauri/tauri.conf.json`, 'utf8'))
const fileConfig = existsSync(releaseConfigPath)
  ? JSON.parse(readFileSync(releaseConfigPath, 'utf8'))
  : {}
const releaseConfig = validateReleaseConfig(
  resolveReleaseConfig(baseConfig, fileConfig, process.env),
  { mode: 'release' },
)

run('pnpm', [
  '-C',
  'vendor/deepseek-harness',
  '--filter',
  '@deepseek-ai/dsh-web-frontend',
  'run',
  'build',
])
if (!existsSync(`${frontendDist}/index.html`)) {
  throw new Error(`frontend build did not produce ${frontendDist}/index.html`)
}

rmSync(desktopFrontendDist, { recursive: true, force: true })
mkdirSync(desktopFrontendDist, { recursive: true })
cpSync(frontendDist, desktopFrontendDist, { recursive: true, dereference: true })

run(process.execPath, [`${repoRoot}scripts/desktop/package-sidecar.mjs`])

const runtimeVersion = `${desktopRoot}src-tauri/resources/agent-sidecar/runtime/package.json`
if (!existsSync(runtimeVersion)) {
  throw new Error(`sidecar runtime was not produced: ${runtimeVersion}`)
}

const tauriOverride = JSON.stringify({
  build: { frontendDist: '../web-release' },
  bundle: {
    createUpdaterArtifacts: true,
    resources: { 'resources/agent-sidecar/': 'agent-sidecar/' },
  },
  plugins: { updater: releaseConfig.plugins.updater },
})
run('pnpm', ['--dir', desktopRoot, 'exec', 'tauri', 'build', '--config', tauriOverride])

const releaseNote = `${desktopRoot}src-tauri/target/release/bundle`
writeFileSync(
  `${desktopRoot}web-release/.physicsos-release`,
  'Generated by scripts/desktop/package-release.mjs. Do not edit by hand.\n',
)
process.stdout.write(`release frontend: ${desktopFrontendDist}\n`)
process.stdout.write(`release bundles: ${releaseNote}\n`)
