import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import {
  localUnsignedEnvironment,
  parseRustTargetTriple,
  resolveReleaseConfig,
  rustTargetTriple,
  validateReleaseConfig,
} from './release-lib.mjs'

const repoRoot = fileURLToPath(new URL('../..', import.meta.url))
const desktopRoot = `${repoRoot}apps/desktop/`
const vendorRoot = `${repoRoot}vendor/deepseek-harness/`
// vendor/deepseek-harness/apps/web/dist is the canonical Vite output.
const frontendDist = `${vendorRoot}apps/web/dist`
const desktopFrontendDist = `${desktopRoot}web-release`
const releaseConfigPath =
  process.env.PHYSICSOS_DESKTOP_RELEASE_CONFIG ?? `${desktopRoot}release.config.json`
const pnpmEnvironment = {
  ...process.env,
  pnpm_config_verify_deps_before_run: 'false',
}
const args = process.argv.slice(2)

function argumentValue(name, fallback) {
  const inline = args.find((argument) => argument.startsWith(`${name}=`))
  if (inline !== undefined) return inline.slice(name.length + 1)
  const index = args.indexOf(name)
  return index === -1 ? fallback : args[index + 1]
}

function hasArgument(name, environmentName) {
  return args.includes(name) || process.env[environmentName] === '1'
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    env: pnpmEnvironment,
    stdio: 'inherit',
    ...options,
  })
  if (result.error) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
  return result
}

const target =
  argumentValue('--target', process.env.PHYSICSOS_DESKTOP_TARGET ?? rustTargetTriple()) ??
  rustTargetTriple()
const targetParts = parseRustTargetTriple(target)
const bundles =
  argumentValue('--bundles', process.env.PHYSICSOS_DESKTOP_BUNDLES)?.replaceAll(' ', '') ?? null
const unsigned = hasArgument('--unsigned', 'PHYSICSOS_DESKTOP_UNSIGNED')
const noUpdaterSigning =
  unsigned || hasArgument('--no-updater-signing', 'PHYSICSOS_DESKTOP_NO_UPDATER_SIGNING')
const noSign = unsigned || hasArgument('--no-sign', 'PHYSICSOS_DESKTOP_NO_SIGN')
const allowCrossBuild = args.includes('--allow-cross-build')
const skipSidecarBuild = hasArgument('--skip-sidecar-build', 'PHYSICSOS_DESKTOP_SKIP_SIDECAR_BUILD')

const baseConfig = JSON.parse(readFileSync(`${desktopRoot}src-tauri/tauri.conf.json`, 'utf8'))
const fileConfig = existsSync(releaseConfigPath)
  ? JSON.parse(readFileSync(releaseConfigPath, 'utf8'))
  : {}
const releaseConfig = resolveReleaseConfig(baseConfig, fileConfig, process.env)
releaseConfig.bundle.createUpdaterArtifacts = !noUpdaterSigning
validateReleaseConfig(releaseConfig, {
  mode: 'release',
  requiresUpdaterArtifacts: !noUpdaterSigning,
})

run('pnpm', [
  '-C',
  'vendor/deepseek-harness',
  '--filter',
  '@deepseek-ai/dsh-web-frontend',
  'run',
  'build',
])
if (!existsSync(`${frontendDist}/index.html`)) {
  throw new Error(`frontend build did not produce ${frontendDist}/index.html`)
}

rmSync(desktopFrontendDist, { recursive: true, force: true })
mkdirSync(desktopFrontendDist, { recursive: true })
cpSync(frontendDist, desktopFrontendDist, { recursive: true, dereference: true })

run(process.execPath, [
  `${repoRoot}scripts/desktop/package-sidecar.mjs`,
  '--platform',
  targetParts.platform,
  '--arch',
  targetParts.architecture,
  ...(skipSidecarBuild ? ['--skip-build'] : []),
  ...(allowCrossBuild ? ['--allow-cross-build'] : []),
])

const runtimeVersion = `${desktopRoot}src-tauri/resources/agent-sidecar/runtime/package.json`
if (!existsSync(runtimeVersion)) {
  throw new Error(`sidecar runtime was not produced: ${runtimeVersion}`)
}

const tauriOverride = JSON.stringify({
  build: { frontendDist: '../web-release' },
  bundle: {
    createUpdaterArtifacts: releaseConfig.bundle.createUpdaterArtifacts,
    resources: { 'resources/agent-sidecar/': 'agent-sidecar/' },
  },
  plugins: { updater: releaseConfig.plugins.updater },
})
const tauriArgs = [
  '--dir',
  desktopRoot,
  'exec',
  'tauri',
  'build',
  '--config',
  tauriOverride,
  '--target',
  target,
]
if (bundles !== null && bundles.length > 0) tauriArgs.push('--bundles', bundles)
if (noSign) tauriArgs.push('--no-sign')
run('pnpm', tauriArgs, {
  env: {
    ...(unsigned ? localUnsignedEnvironment(process.env) : process.env),
    CI: process.env.CI ?? 'true',
  },
})

const releaseBundles = `${desktopRoot}src-tauri/target/${target}/release/bundle`
writeFileSync(
  `${desktopRoot}web-release/.physicsos-release`,
  'Generated by scripts/desktop/package-release.mjs. Do not edit by hand.\n',
)
process.stdout.write(`release frontend: ${desktopFrontendDist}\n`)
process.stdout.write(`release target: ${target}\n`)
process.stdout.write(`release bundles: ${releaseBundles}\n`)
process.stdout.write(`release signing: ${noUpdaterSigning ? 'unsigned updater' : 'signed updater'}`)
process.stdout.write(`${noSign ? ', unsigned app' : ', code signing enabled'}\n`)
