export {
  PHYSICS_SCENE_SCHEMA,
  type Ammeter,
  type Body,
  type Boundary,
  type BoundaryBehavior,
  type BoundaryType,
  type Capacitor,
  type Circuit,
  type CircuitComponent,
  type CircuitComponentBase,
  type CircuitConnection,
  type CircuitNode,
  type CircuitSwitch,
  type CircuitTerminal,
  type Constraint,
  type ConstraintType,
  type CoordinateSystem,
  type Field,
  type FieldBase,
  type Force,
  type ForceType,
  type GravityField,
  type Inductor,
  type InductionBench,
  type InductionBenchType,
  type MaterialDefinition,
  type MeasurementDefinition,
  type ObservableDefinition,
  type ObservationStyle,
  type ObservableType,
  type OpticalBench,
  type OpticalElement,
  type OpticalElementBase,
  type OpticalObject,
  type OpticalScreen,
  type Particle,
  type PhysicsObjectBase,
  type PhysicsScene,
  type PointChargeField,
  type Region,
  type RegionShape,
  type Resistor,
  type SceneAnnotation,
  type SceneDimension,
  type SceneLineage,
  type SceneMetadata,
  type ShapeDefinition,
  type ThinLens,
  type PlaneMirror,
  type CurvedMirror,
  type AcousticBench,
  type AcousticReflector,
  type AcousticSource,
  type FluidTank,
  type SubmergedBlock,
  type TankLiquid,
  type ThermalBench,
  type TransformerBench,
  type ThermometerBench,
  type NoiseBench,
  type ThermalSample,
  type LeverBench,
  type LightBench,
  type LeverHanger,
  type LeverHangerSide,
  type PressureBench,
  type PressureBenchType,
  type CurrentBench,
  type CurrentBenchType,
  type CyclotronBench,
  type EnergyBench,
  type WaveBench,
  type WaveBenchType,
  type ModernPhysicsBench,
  type ModernPhysicsBenchType,
  type Timeline,
  type TimelineState,
  type UniformElectricField,
  type UniformMagneticField,
  type VariableResistor,
  type Voltmeter,
  type VoltageSource,
} from './scene.ts'
export { defaultCoordinateSystem, validateScene } from './scene-validation.ts'
export {
  PHYSICS_EVENT_SCHEMA,
  SCENE_COMMAND_SCHEMA,
  SCENE_REVISION_CONFLICT,
  SceneRuntime,
  SceneStore,
  type PhysicsEvent,
  type PhysicsEventEnvelope,
  type PhysicsEventPayload,
  type PhysicsEventPayloadMap,
  type PhysicsEventType,
  type SceneCommand,
  type SceneCommandEnvelope,
  type SceneCommandFailure,
  type SceneCommandPayload,
  type SceneCommandPayloadMap,
  type SceneCommandResult,
  type SceneCommandSuccess,
  type SceneCommandType,
  type SceneRuntimeOptions,
  type ElectricFieldDirection,
} from './scene-runtime.ts'
export {
  cloneVector,
  createMagneticScene,
  createSceneCommand,
  type MagneticObservableKey,
  type MagneticSceneInput,
  type SceneCommandInput,
} from './magnetic-scene-factory.ts'
export {
  createElectricScene,
  type ElectricObservableKey,
  type ElectricSceneInput,
} from './electric-scene-factory.ts'
export {
  createMechanicsScene,
  createMechanicsSimulationRequest,
  type MechanicsModelId,
  type MechanicsSceneInput,
} from './mechanics-scene-factory.ts'
export {
  forkExperimentalScene,
  isExperimentalBranch,
  type ForkExperimentalSceneInput,
} from './scene-branch.ts'
export {
  pointChargeField,
  pointChargeParticle,
  probeParticle,
  probeParticleOf,
  sourceChargesOf,
  type PointChargeInput,
  type ProbeParticleInput,
} from './electric/point-charge.ts'
export {
  uniformElectricField,
  uniformFieldAxisOf,
  type UniformFieldAxis,
} from './electric/electric-field.ts'
export {
  createPointChargeScene,
  fieldSamplePointOf,
  type PointChargeSceneInput,
} from './electric/electric-scene-builder.ts'
export {
  createParallelPlateScene,
  isParallelPlateScene,
  plateLengthOf,
  plateSeparationOf,
  type ParallelPlateObservableKey,
  type ParallelPlateSceneInput,
} from './electric/parallel-plate.ts'
export {
  SAMPLEABLE_REGION_SHAPES,
  gravityFieldsOf,
  hasUnsampleableRegion,
  isCompositeFieldScene,
  pointInRegion,
  sameFieldEnvironment,
  sampleFieldsAt,
  uniformElectricFieldsOf,
  uniformMagneticFieldsOf,
  type FieldSample,
} from './composite/composite-field.ts'
export {
  createCompositeFieldScene,
  createMassSpectrometerScene,
  createMultiRegionFieldScene,
  createVelocitySelectorScene,
  type CompositeElectricDirection,
  type CompositeObservableKey,
  type CompositeSceneInput,
  type MagneticOrientation,
  type MassSpectrometerSceneInput,
  type MultiRegionFieldSceneInput,
  type VelocitySelectorSceneInput,
} from './composite/composite-scene-factory.ts'
export {
  createCyclotronScene,
  cyclotronBenchOf,
  cyclotronBenchesOf,
  isCyclotronScene,
  type CyclotronSceneInput,
} from './composite/cyclotron-scene.ts'
export {
  CIRCUIT_SWEEP_DURATION_SECONDS,
  CIRCUIT_SYMBOL_HALF_LENGTH,
  SOURCE_TERMINAL_KEYS,
  TWO_TERMINAL_KEYS,
  circuitComponentOf,
  circuitLayoutOf,
  circuitLayoutPlace,
  circuitOf,
  circuitRotationVector,
  circuitTerminalId,
  circuitTerminalPoint,
  createCircuitScene,
  isCircuitScene,
  terminalKeysOf,
  variableResistorsOf,
  type CircuitComponentPlacement,
  type CircuitComponentSpec,
  type CircuitLayout,
  type CircuitObservableKey,
  type CircuitSceneInput,
} from './circuit/circuit-scene.ts'
export {
  createEmfMeasurementScene,
  createMixedCircuitScene,
  createParallelCircuitScene,
  createRheostatCircuitScene,
  createSeriesCircuitScene,
  createShortCircuitScene,
  type EmfMeasurementInput,
  type ShortCircuitInput,
  type MixedCircuitInput,
  type ParallelCircuitInput,
  type RheostatCircuitInput,
  type SeriesCircuitInput,
} from './circuit/circuit-templates.ts'
export {
  createOpticalBenchScene,
  curvedMirrorOf,
  isOpticsScene,
  opticalBenchOf,
  opticalBenchesOf,
  opticalElementOf,
  thinLensOf,
  type OpticalBenchSceneInput,
  type OpticalElementSpec,
  type OpticalObjectSpec,
  type OpticalScreenSpec,
  type OpticsObservableKey,
} from './optics/optics-scene.ts'
export {
  createConcaveMirrorScene,
  createConvexLensScene,
  createConvexMirrorScene,
  createPlaneMirrorScene,
  type ConcaveMirrorSceneInput,
  type ConvexLensSceneInput,
  type ConvexMirrorSceneInput,
  type PlaneMirrorSceneInput,
} from './optics/optics-templates.ts'
export {
  acousticBenchOf,
  acousticBenchesOf,
  createAcousticBenchScene,
  isAcousticsScene,
  type AcousticBenchSceneInput,
  type AcousticReflectorSpec,
  type AcousticSourceSpec,
  type AcousticsObservableKey,
} from './acoustics/acoustics-scene.ts'
export {
  createEchoRangingScene,
  type EchoRangingSceneInput,
} from './acoustics/acoustics-templates.ts'
export {
  createFluidTankScene,
  fluidTankOf,
  fluidTanksOf,
  isFluidScene,
  type FluidObservableKey,
  type FluidTankSceneInput,
  type SubmergedBlockSpec,
  type TankLiquidSpec,
} from './fluid/fluid-scene.ts'
export { createArchimedesScene, type ArchimedesSceneInput } from './fluid/fluid-templates.ts'
export {
  createPressureBenchScene,
  isPressureScene,
  pressureBenchOf,
  pressureBenchesOf,
  type AtmosphericPressureSpec,
  type LiquidPressureSpec,
  type PressureBenchSceneInput,
  type PressureBenchSpec,
  type PressureObservableKey,
  type SolidPressureSpec,
} from './fluid/pressure-scene.ts'
export {
  createAtmosphericPressureScene,
  createLiquidPressureScene,
  createSolidPressureScene,
  type AtmosphericPressureSceneInput,
  type LiquidPressureSceneInput,
  type SolidPressureSceneInput,
} from './fluid/pressure-templates.ts'
export {
  createLightBenchScene,
  isLightScene,
  lightBenchOf,
  lightBenchesOf,
  type LightBenchSceneInput,
  type LightObservableKey,
} from './optics/light-scene.ts'
export {
  createPinholeScene,
  createTotalReflectionScene,
  type PinholeSceneInput,
  type TotalReflectionSceneInput,
} from './optics/light-templates.ts'
export {
  createNoiseBenchScene,
  isNoiseScene,
  noiseBenchOf,
  noiseBenchesOf,
  type NoiseBenchSceneInput,
  type NoiseObservableKey,
} from './acoustics/noise-scene.ts'
export {
  createNoiseBarrierScene,
  type NoiseBarrierSceneInput,
} from './acoustics/noise-templates.ts'
export {
  createThermometerBenchScene,
  isThermometerScene,
  thermometerBenchOf,
  thermometerBenchesOf,
  type ThermometerBenchSceneInput,
  type ThermometerObservableKey,
} from './thermal/thermometer-scene.ts'
export {
  createThermometerCalibrationScene,
  type ThermometerCalibrationSceneInput,
} from './thermal/thermometer-templates.ts'
export {
  createTransformerBenchScene,
  isTransformerScene,
  transformerBenchOf,
  transformerBenchesOf,
  type TransformerBenchSceneInput,
  type TransformerObservableKey,
} from './transformer/transformer-scene.ts'
export {
  createEnergyBenchScene,
  energyBenchOf,
  energyBenchesOf,
  isEnergyScene,
  type EnergyBenchSceneInput,
  type EnergyObservableKey,
} from './energy/energy-scene.ts'
export {
  createMechanicalEnergyScene,
  createRampFrictionScene,
  type MechanicalEnergySceneInput,
  type RampFrictionSceneInput,
} from './energy/energy-templates.ts'
export {
  createCurrentBenchScene,
  currentBenchOf,
  currentBenchesOf,
  isCurrentScene,
  type CurrentBenchSceneInput,
  type CurrentBenchSpec,
  type CurrentObservableKey,
  type ElectromagnetSpec,
  type MotorSpec,
  type SolenoidFieldSpec,
  type StraightWireFieldSpec,
} from './magnetic/current-scene.ts'
export {
  createElectromagnetScene,
  createMotorScene,
  createSolenoidFieldScene,
  createStraightWireFieldScene,
  type ElectromagnetSceneInput,
  type MotorSceneInput,
  type SolenoidFieldSceneInput,
  type StraightWireFieldSceneInput,
} from './magnetic/current-templates.ts'
export {
  CELSIUS_ZERO_IN_KELVIN,
  createThermalBenchScene,
  isThermalScene,
  thermalBenchOf,
  thermalBenchesOf,
  type ThermalBenchSceneInput,
  type ThermalObservableKey,
  type ThermalSampleSpec,
} from './thermal/thermal-scene.ts'
export {
  createBoilingWaterScene,
  createCrystalMeltingScene,
  createHeatCapacityComparisonScene,
  type BoilingWaterSceneInput,
  type CrystalMeltingSceneInput,
  type HeatCapacityComparisonSceneInput,
} from './thermal/thermal-templates.ts'
export {
  createLeverBenchScene,
  isLeverScene,
  leverBenchOf,
  leverBenchesOf,
  type LeverBenchSceneInput,
  type LeverHangerSpec,
  type LeverObservableKey,
} from './lever/lever-scene.ts'
export { createLeverBalanceScene, type LeverBalanceSceneInput } from './lever/lever-templates.ts'
export {
  createInductionScene,
  inductionBenchOf,
  inductionBenchesOf,
  inductionTypeOf,
  isInductionScene,
  type BarMotionSpec,
  type DoubleBarRailSpec,
  type FluxChangeSpec,
  type InductionBenchSceneInput,
  type InductionBenchSpec,
  type InductionObservableKey,
} from './induction/induction-scene.ts'
export {
  createBarMotionScene,
  createDoubleBarRailScene,
  createFluxChangeScene,
  type BarMotionSceneInput,
  type DoubleBarRailSceneInput,
  type FluxChangeSceneInput,
} from './induction/induction-templates.ts'
export {
  createWaveScene,
  isWaveScene,
  waveBenchOf,
  waveBenchesOf,
  waveTypeOf,
  type InterferenceWaveSpec,
  type LongitudinalWaveSpec,
  type ReflectionRefractionWaveSpec,
  type DiffractionWaveSpec,
  type DopplerWaveSpec,
  type StandingWaveSpec,
  type TravellingWaveSpec,
  type WaveBenchSceneInput,
  type WaveBenchSpec,
  type WaveObservableKey,
} from './wave/wave-scene.ts'
export {
  createStandingWaveScene,
  createTravellingWaveScene,
  createWaveInterferenceScene,
  createLongitudinalWaveScene,
  createReflectionRefractionScene,
  createDiffractionScene,
  createDopplerScene,
  type DopplerWaveSceneInput,
  type DiffractionWaveSceneInput,
  type InterferenceWaveSceneInput,
  type LongitudinalWaveSceneInput,
  type ReflectionRefractionSceneInput,
  type StandingWaveSceneInput,
  type TravellingWaveSceneInput,
} from './wave/wave-templates.ts'
export {
  ELECTRON_VOLT_JOULES,
  createModernPhysicsScene,
  createPhotoelectricEffectScene,
  isModernPhysicsScene,
  modernPhysicsBenchOf,
  modernPhysicsBenchesOf,
  type ModernPhysicsSceneInput,
} from './modern/modern-physics-scene.ts'
export {
  MAX_TRAJECTORY_RENDER_POINTS,
  MAX_TRAJECTORY_STORAGE_SAMPLES,
  chunkTrajectoryPoints,
  decimateTrajectoryPoints,
  trajectorySampleTimes,
  trajectoryStorageSampleCount,
} from './trajectory-sampling.ts'
export {
  createCollisionScene,
  createCollisionSimulationRequest,
  type CollisionBodySpec,
  type CollisionSceneInput,
} from './collision/collision-scene-factory.ts'
