export {
  PHYSICS_SCENE_SCHEMA,
  type Ammeter,
  type Body,
  type Boundary,
  type BoundaryBehavior,
  type BoundaryType,
  type Capacitor,
  type Circuit,
  type CircuitComponent,
  type CircuitComponentBase,
  type CircuitConnection,
  type CircuitNode,
  type CircuitSwitch,
  type CircuitTerminal,
  type Constraint,
  type ConstraintType,
  type CoordinateSystem,
  type Field,
  type FieldBase,
  type Force,
  type ForceType,
  type GravityField,
  type Inductor,
  type MaterialDefinition,
  type MeasurementDefinition,
  type ObservableDefinition,
  type ObservationStyle,
  type ObservableType,
  type OpticalBench,
  type OpticalElement,
  type OpticalElementBase,
  type OpticalObject,
  type OpticalScreen,
  type Particle,
  type PhysicsObjectBase,
  type PhysicsScene,
  type PointChargeField,
  type Region,
  type RegionShape,
  type Resistor,
  type SceneAnnotation,
  type SceneDimension,
  type SceneLineage,
  type SceneMetadata,
  type ShapeDefinition,
  type ThinLens,
  type PlaneMirror,
  type CurvedMirror,
  type Timeline,
  type TimelineState,
  type UniformElectricField,
  type UniformMagneticField,
  type VariableResistor,
  type Voltmeter,
  type VoltageSource,
} from './scene.ts'
export { defaultCoordinateSystem, validateScene } from './scene-validation.ts'
export {
  PHYSICS_EVENT_SCHEMA,
  SCENE_COMMAND_SCHEMA,
  SCENE_REVISION_CONFLICT,
  SceneRuntime,
  SceneStore,
  type PhysicsEvent,
  type PhysicsEventEnvelope,
  type PhysicsEventPayload,
  type PhysicsEventPayloadMap,
  type PhysicsEventType,
  type SceneCommand,
  type SceneCommandEnvelope,
  type SceneCommandFailure,
  type SceneCommandPayload,
  type SceneCommandPayloadMap,
  type SceneCommandResult,
  type SceneCommandSuccess,
  type SceneCommandType,
  type SceneRuntimeOptions,
  type ElectricFieldDirection,
} from './scene-runtime.ts'
export {
  cloneVector,
  createMagneticScene,
  createSceneCommand,
  type MagneticObservableKey,
  type MagneticSceneInput,
  type SceneCommandInput,
} from './magnetic-scene-factory.ts'
export {
  createElectricScene,
  type ElectricObservableKey,
  type ElectricSceneInput,
} from './electric-scene-factory.ts'
export {
  createMechanicsScene,
  createMechanicsSimulationRequest,
  type MechanicsModelId,
  type MechanicsSceneInput,
} from './mechanics-scene-factory.ts'
export {
  forkExperimentalScene,
  isExperimentalBranch,
  type ForkExperimentalSceneInput,
} from './scene-branch.ts'
export {
  pointChargeField,
  pointChargeParticle,
  probeParticle,
  probeParticleOf,
  sourceChargesOf,
  type PointChargeInput,
  type ProbeParticleInput,
} from './electric/point-charge.ts'
export {
  uniformElectricField,
  uniformFieldAxisOf,
  type UniformFieldAxis,
} from './electric/electric-field.ts'
export {
  createPointChargeScene,
  fieldSamplePointOf,
  type PointChargeSceneInput,
} from './electric/electric-scene-builder.ts'
export {
  createParallelPlateScene,
  isParallelPlateScene,
  plateLengthOf,
  plateSeparationOf,
  type ParallelPlateObservableKey,
  type ParallelPlateSceneInput,
} from './electric/parallel-plate.ts'
export {
  SAMPLEABLE_REGION_SHAPES,
  gravityFieldsOf,
  hasUnsampleableRegion,
  isCompositeFieldScene,
  pointInRegion,
  sameFieldEnvironment,
  sampleFieldsAt,
  uniformElectricFieldsOf,
  uniformMagneticFieldsOf,
  type FieldSample,
} from './composite/composite-field.ts'
export {
  createCompositeFieldScene,
  createMassSpectrometerScene,
  createMultiRegionFieldScene,
  createVelocitySelectorScene,
  type CompositeElectricDirection,
  type CompositeObservableKey,
  type CompositeSceneInput,
  type MagneticOrientation,
  type MassSpectrometerSceneInput,
  type MultiRegionFieldSceneInput,
  type VelocitySelectorSceneInput,
} from './composite/composite-scene-factory.ts'
export {
  CIRCUIT_SWEEP_DURATION_SECONDS,
  CIRCUIT_SYMBOL_HALF_LENGTH,
  SOURCE_TERMINAL_KEYS,
  TWO_TERMINAL_KEYS,
  circuitComponentOf,
  circuitLayoutOf,
  circuitOf,
  circuitRotationVector,
  circuitTerminalId,
  circuitTerminalPoint,
  createCircuitScene,
  isCircuitScene,
  terminalKeysOf,
  variableResistorsOf,
  type CircuitComponentPlacement,
  type CircuitComponentSpec,
  type CircuitLayout,
  type CircuitObservableKey,
  type CircuitSceneInput,
} from './circuit/circuit-scene.ts'
export {
  createEmfMeasurementScene,
  createMixedCircuitScene,
  createParallelCircuitScene,
  createRheostatCircuitScene,
  createSeriesCircuitScene,
  type EmfMeasurementInput,
  type MixedCircuitInput,
  type ParallelCircuitInput,
  type RheostatCircuitInput,
  type SeriesCircuitInput,
} from './circuit/circuit-templates.ts'
export {
  createOpticalBenchScene,
  curvedMirrorOf,
  isOpticsScene,
  opticalBenchOf,
  opticalBenchesOf,
  opticalElementOf,
  thinLensOf,
  type OpticalBenchSceneInput,
  type OpticalElementSpec,
  type OpticalObjectSpec,
  type OpticalScreenSpec,
  type OpticsObservableKey,
} from './optics/optics-scene.ts'
export {
  createConcaveMirrorScene,
  createConvexLensScene,
  createPlaneMirrorScene,
  type ConcaveMirrorSceneInput,
  type ConvexLensSceneInput,
  type PlaneMirrorSceneInput,
} from './optics/optics-templates.ts'
